"""drop room_info.ri_max

Revision ID: e1fa6dfd9ae3
Revises: f1ca5f54a909
Create Date: 2026-09-23 23:29:07.809891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fa6dfd9ae3'
down_revision = 'f1ca5f54a909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROOM_INFO', schema=None) as batch_op:
        batch_op.drop_column('RI_MAX')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ROOM_INFO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RI_MAX', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
