"""create initial tables

Revision ID: f1ca5f54a909
Revises: 
Create Date: 2026-09-19 01:40:08.168691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ca5f54a909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ROOM_INFO',
    sa.Column('RI_ID', sa.Integer(), nullable=False),
    sa.Column('RI_NAME', sa.String(length=50), nullable=True),
    sa.Column('RI_TYPE', sa.CHAR(length=1), nullable=False),
    sa.Column('RI_MAX', sa.Integer(), nullable=False),
    sa.Column('RI_RDATE', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('RI_ID')
    )
    op.create_table('USER_INFO',
    sa.Column('UI_ID', sa.String(length=50), nullable=False),
    sa.Column('UI_PW', sa.String(length=255), nullable=False),
    sa.Column('UI_NAME', sa.String(length=50), nullable=False),
    sa.Column('UI_MAIL', sa.String(length=50), nullable=False),
    sa.Column('UI_RDATE', sa.Date(), nullable=False),
    sa.Column('UI_WITHDRAWN', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('UI_ID'),
    sa.UniqueConstraint('UI_MAIL')
    )
    op.create_table('CHAT_MESSAGE',
    sa.Column('CM_ID', sa.Integer(), nullable=False),
    sa.Column('RI_ID', sa.Integer(), nullable=False),
    sa.Column('UI_ID', sa.String(length=50), nullable=False),
    sa.Column('CM_MESSAGE', sa.String(length=255), nullable=False),
    sa.Column('CM_DATE', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RI_ID'], ['ROOM_INFO.RI_ID'], ),
    sa.ForeignKeyConstraint(['UI_ID'], ['USER_INFO.UI_ID'], ),
    sa.PrimaryKeyConstraint('CM_ID')
    )
    op.create_table('ROOM_MEMBER',
    sa.Column('RM_ID', sa.Integer(), nullable=False),
    sa.Column('RI_ID', sa.Integer(), nullable=False),
    sa.Column('UI_ID', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['RI_ID'], ['ROOM_INFO.RI_ID'], ),
    sa.ForeignKeyConstraint(['UI_ID'], ['USER_INFO.UI_ID'], ),
    sa.PrimaryKeyConstraint('RM_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ROOM_MEMBER')
    op.drop_table('CHAT_MESSAGE')
    op.drop_table('USER_INFO')
    op.drop_table('ROOM_INFO')
    # ### end Alembic commands ###
